import java.util.Scanner;

class Exception4
{
    public static void main(String Arg[])
    {
        try
        {
            // Code
        }
        catch(ArrayIndexOutOfBoundsException obj)
        {
        }
        catch(ArithematicException obj)
        {
        }
        catch(Exception obj)
        {
        }
        finally
        {
            System.out.println("Inside finally block");
        }
    }
}